---
config:
  flowchart:
    curve: linear
---
graph TD;
	__start__([<p>__start__</p>]):::first
	data_collection(data_collection)
	vulnerability_analysis(vulnerability_analysis)
	physical_risk_score(physical_risk_score)
	aal_analysis(aal_analysis)
	report_template(report_template)
	strategy_generation(strategy_generation)
	report_generation(report_generation)
	validation(validation)
	finalization(finalization)
	__end__([<p>__end__</p>]):::last
	__start__ --> data_collection;
	aal_analysis --> physical_risk_score;
	data_collection --> vulnerability_analysis;
	physical_risk_score --> report_template;
	report_generation --> validation;
	report_template --> strategy_generation;
	strategy_generation --> report_generation;
	validation -.-> finalization;
	validation -.-> strategy_generation;
	vulnerability_analysis --> aal_analysis;
	finalization --> __end__;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc
