---
config:
  flowchart:
    curve: linear
---
graph TD;
	__start__([<p>__start__</p>]):::first
	collect_data(collect_data)
	calculate_ssp(calculate_ssp)
	analyze_high_temperature(analyze_high_temperature)
	analyze_cold_wave(analyze_cold_wave)
	analyze_sea_level_rise(analyze_sea_level_rise)
	analyze_drought(analyze_drought)
	analyze_wildfire(analyze_wildfire)
	analyze_typhoon(analyze_typhoon)
	analyze_water_scarcity(analyze_water_scarcity)
	analyze_flood(analyze_flood)
	integrate_risks(integrate_risks)
	generate_report(generate_report)
	__end__([<p>__end__</p>]):::last
	__start__ --> collect_data;
	analyze_cold_wave --> integrate_risks;
	analyze_drought --> integrate_risks;
	analyze_flood --> integrate_risks;
	analyze_high_temperature --> integrate_risks;
	analyze_sea_level_rise --> integrate_risks;
	analyze_typhoon --> integrate_risks;
	analyze_water_scarcity --> integrate_risks;
	analyze_wildfire --> integrate_risks;
	calculate_ssp --> analyze_cold_wave;
	calculate_ssp --> analyze_drought;
	calculate_ssp --> analyze_flood;
	calculate_ssp --> analyze_high_temperature;
	calculate_ssp --> analyze_sea_level_rise;
	calculate_ssp --> analyze_typhoon;
	calculate_ssp --> analyze_water_scarcity;
	calculate_ssp --> analyze_wildfire;
	collect_data --> calculate_ssp;
	integrate_risks --> generate_report;
	generate_report --> __end__;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc
