---
config:
  flowchart:
    curve: linear
---
graph TD;
	__start__([<p>__start__</p>]):::first
	data_collection(data_collection)
	building_characteristics(building_characteristics)
	report_template(report_template)
	impact_analysis(impact_analysis)
	strategy_generation(strategy_generation)
	report_generation(report_generation)
	validation(validation)
	refiner(refiner)
	finalization(finalization)
	__end__([<p>__end__</p>]):::last
	__start__ --> data_collection;
	building_characteristics --> validation;
	data_collection --> report_template;
	impact_analysis --> strategy_generation;
	refiner --> validation;
	report_generation --> validation;
	report_template --> building_characteristics;
	report_template --> impact_analysis;
	strategy_generation --> report_generation;
	validation -.-> building_characteristics;
	validation -.-> finalization;
	validation -.-> impact_analysis;
	validation -.-> refiner;
	validation -.-> strategy_generation;
	finalization --> __end__;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc
